# Generated by Django 4.1.3 on 2022-11-27 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=20, verbose_name='Фамилия')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('login', models.CharField(max_length=10, verbose_name='Логин')),
                ('password', models.CharField(max_length=10, verbose_name='Пароль')),
                ('about', models.TextField(verbose_name='О себе')),
                ('github_link', models.CharField(max_length=200, verbose_name='Ccылка на github')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Номер телефона')),
                ('specialization', models.CharField(max_length=200, verbose_name='Специализация')),
            ],
        ),
    ]
