# Generated by Django 4.1.3 on 2022-11-28 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'Аккаунт', 'verbose_name_plural': 'Аккаунты'},
        ),
        migrations.AlterField(
            model_name='users',
            name='about',
            field=models.TextField(null=True, verbose_name='О себе'),
        ),
        migrations.AlterField(
            model_name='users',
            name='birth_date',
            field=models.DateField(null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='users',
            name='github_link',
            field=models.CharField(max_length=200, null=True, verbose_name='Ccылка на github'),
        ),
        migrations.AlterField(
            model_name='users',
            name='last_name',
            field=models.CharField(max_length=20, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='users',
            name='login',
            field=models.CharField(max_length=10, null=True, verbose_name='Логин'),
        ),
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(max_length=20, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=100, null=True, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='users',
            name='phone_number',
            field=models.CharField(max_length=15, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='users',
            name='specialization',
            field=models.CharField(max_length=200, null=True, verbose_name='Специализация'),
        ),
    ]
