# Generated by Django 4.1.3 on 2022-11-28 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_users_options_alter_users_about_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='telegram',
            field=models.CharField(max_length=200, null=True, verbose_name='Ник в телеграм'),
        ),
    ]
